### ISSUE TITLE
Cumulus offset speed bug with fix.

### ISSUE THREAD

**Issue by jacobcoughenour** [7leodev/UniversalSky#8]
I was unable to change the clouds_cumulus_offset_speed property from the editor.
Upon looking in SkyManager I found the culprit.
https://github.com/7leodev/UniversalSky/blob/bbbdb4a591ec0ab7231444b96613ba323a2e4549/addons/jc.godot.universal-sky/Code/Sky/SkyManager.gd#L666-L669

set_clouds_cumulus_offset_speed() is changing the clouds_offset_speed instead of clouds_cumulus_offset_speed.
Changing line 668 to ```clouds_cumulus_offset_speed = value``` fixes this problem.

**Comment by 7leodev** [comment]
Thanks for reporting.
